=== KaterynaHartseva93/final-task/webapp/WEB-INF/access/access.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.market.com/access" xmlns:tns="http://www.market.com/access">
	<xsd:element name="presentation">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="page-view" type="tns:page-view"
					maxOccurs="unbounded">
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="page-view">
		<xsd:sequence>
			<xsd:element name="role" type="tns:role" />
			<xsd:element name="home-page" type="xsd:string" />
			<xsd:element name="page-categories" type="tns:page-categories"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="page-categories">
		<xsd:sequence>
			<xsd:element name="page-category" type="tns:page-category"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="page-category">
		<xsd:sequence>
			<xsd:element name="page-category-key" type="xsd:string" />
			<xsd:element name="page-category-path" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="role">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="ADMIN" />
			<xsd:enumeration value="GUEST" />
			<xsd:enumeration value="CLIENT" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== KaterynaHartseva93/final-task/webapp/WEB-INF/access/access.xml
<?xml version="1.0" encoding="UTF-8"?>
<market:presentation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:market="http://www.market.com/access" xsi:schemaLocation="http://www.market.com/access access.xsd">
	<page-view>
		<role>GUEST</role>
		<home-page>main</home-page>
		<page-categories>
			<page-category>
				<page-category-key>main</page-category-key>
				<page-category-path>/controller/main</page-category-path>
			</page-category>
			<page-category>
				<page-category-key>clothes</page-category-key>
				<page-category-path>/controller/clothes</page-category-path>
			</page-category>
			<page-category>
				<page-category-key>cart</page-category-key>
				<page-category-path>/controller/cart</page-category-path>
			</page-category>
		</page-categories>
	</page-view>
	<page-view>
		<role>CLIENT</role>
		<home-page>main</home-page>
		<page-categories>
			<page-category>
				<page-category-key>main</page-category-key>
				<page-category-path>/controller/main</page-category-path>
			</page-category>
			<page-category>
				<page-category-key>clothes</page-category-key>
				<page-category-path>/controller/clothes</page-category-path>
			</page-category>
			<page-category>
				<page-category-key>cart</page-category-key>
				<page-category-path>/controller/cart</page-category-path>
			</page-category>
			<page-category>
				<page-category-key>orders</page-category-key>
				<page-category-path>/controller/orders</page-category-path>
			</page-category>
		</page-categories>
	</page-view>
	<page-view>
		<role>ADMIN</role>
		<home-page>clothes</home-page>
		<page-categories>
			<page-category>
				<page-category-key>clothes</page-category-key>
				<page-category-path>/controller/clothes</page-category-path>
			</page-category>
			<page-category>
				<page-category-key>users</page-category-key>
				<page-category-path>/controller/users</page-category-path>
			</page-category>
			<page-category>
				<page-category-key>orders</page-category-key>
				<page-category-path>/controller/orders</page-category-path>
			</page-category>
		</page-categories>
	</page-view>
</market:presentation>
